version: '2'

services:
    api:
        build:
            context: .
            dockerfile: ./api/Dockerfile
        container_name: stock-simulator-api
        image: stock-simulator-api
    queue_etl:
        build:
            context: .
            dockerfile: ./etl/queue_loader/Dockerfile
        container_name: stock-simulator-queue-etl
        image: stock-simulator-queue-etl
    account_value_etl:
        build:
            context: .
            dockerfile: ./etl/account_updater/Dockerfile
        container_name: stock-simulator-account-value-etl
        image: stock-simulator-account-value-etl