paths:
  /api/accounts:
    get:
      summary: Returns all accounts with their users
      tags:
        - Accounts
      parameters:
      - in: header
        name: Authorization
        required: true
        description: "Bearer <token>"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/Accounts"
    post:
      summary: Creates a new account
      tags:
        - Accounts
      parameters:
      - in: header
        name: Authorization
        required: true
        description: "Bearer <token>"
      - in: body
        name: body
        required: true
        properties:
          usd_amount:
            type: "number"
          share_amount:
            type: "number"
          symbol:
            type: "string"
          user_id:
            type: "integer"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/Create Accounts"
        400:
          description: "Invalid request"
          schema:
            $ref: "#/definitions/400 Error"
  /api/accounts/{id}:
      get:
        summary: Returns all accounts belonging to the specified id
        tags:
          - Accounts
        parameters:
        - in: path
          name: "id"
          description: "An account id"
          required: true
          type: integer
        - in: header
          name: Authorization
          required: true
          description: "Bearer <token>"
        responses:
          200:
            description: "OK"
            schema:
              $ref: "#/definitions/Accounts"
          404:
            description: "Not Found"
            schema:
              $ref: "#/definitions/404 Error"
  /api/stocks:
    get:
      summary: Returns all stocks
      tags:
        - Stocks
      parameters:
      - in: header
        name: Authorization
        required: true
        description: "Bearer <token>"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/Stocks"
  /api/stocks/{symbol}:
    get:
      summary: Returns all stocks with the specified symbol
      tags:
        - Stocks
      parameters:
      - in: path
        name: "symbol"
        description: "A stock symbol"
        required: true
        type: string
      - in: header
        name: Authorization
        required: true
        description: "Bearer <token>"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/Stocks"
        404:
          description: "Not Found"
          schema:
            $ref: "#/definitions/404 Error"
  /api/users/{id}:
    get:
      summary: Returns all users with their address belonging to the specified id
      tags:
        - Users
      parameters:
      - in: path
        name: "id"
        description: "A user id"
        required: true
        type: integer
      - in: header
        name: Authorization
        required: true
        description: "Bearer <token>"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/Users"
        404:
          description: "Not Found"
          schema:
            $ref: "#/definitions/404 Error"
    put:
      summary: Updates all attributes present in the request body for the user belonging to the specified id
      tags:
        - Users
      parameters:
      - in: path
        name: "id"
        description: "A user id"
        required: true
        type: integer
      - in: header
        name: Authorization
        required: true
        description: "Bearer <token>"
      - in: body
        name: body
        required: false
        properties:
          first_name:
            type: "string"
          last_name:
            type: "string"
          email:
            type: "string"
          street:
            type: "string"
          postal_code:
            type: "string"
          city:
            type: "string"
          state:
            type: "string"
          country:
            type: "string"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/Users"
        400:
          description: "Invalid request"
          schema:
            $ref: "#/definitions/400 Error"
        404:
          description: "Not Found"
          schema:
            $ref: "#/definitions/404 Error"
    delete:
      summary: Deletes the user belonging to the specified id
      tags:
        - Users
      parameters:
      - in: path
        name: "id"
        description: "A user id"
        required: true
        type: integer
      - in: header
        name: Authorization
        required: true
        description: "Bearer <token>"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/Delete Users"
        404:
          description: "Not Found"
          schema:
            $ref: "#/definitions/404 Error"
  /api/users:
    get:
      summary: Returns all users with their address
      tags:
        - Users
      parameters:
      - in: header
        name: Authorization
        required: true
        description: "Bearer <token>"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/Users"
    post:
      summary: Creates a new user
      tags:
        - Users
      parameters:
      - in: header
        name: Authorization
        required: true
        description: "Bearer <token>"
      - in: body
        name: body
        required: true
        properties:
          first_name:
            type: "string"
          last_name:
            type: "string"
          email:
            type: "string"
          street:
            type: "string"
          postal_code:
            type: "string"
          city:
            type: "string"
          state:
            type: "string"
          country:
            type: "string"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/Create Users"
        400:
          description: "Invalid request"
          schema:
            $ref: "#/definitions/400 Error"
definitions:
  404 Error:
    type: "object"
    properties:
      error:
          type: "object"
          properties:
            message:
              type: "string"
              example: "The requested resource was not found."
            code:
              type: "string"
              example: "404"
      timestamp:
        type: "string"
        example: "Sun, 10 Jan 2021 01:01:45 GMT"
  400 Error:
    type: "object"
    properties:
      error:
          type: "object"
          properties:
            message:
              type: "string"
              example: "Unable to parse authentication token. Invalid request."
            code:
              type: "string"
              example: "400"
      timestamp:
        type: "string"
        example: "Sun, 10 Jan 2021 01:01:45 GMT"
  Stocks:
    type: "object"
    properties:
      data:
        type: "array"
        items:
          type: "object"
          properties:
            stock_id:
              type: "integer"
              example: "1"
            symbol:
              type: "string"
              example: "TSLA"
      timestamp:
        type: "string"
        example: "Sun, 10 Jan 2021 01:01:45 GMT"
  Create Accounts:
    type: "object"
    properties:
      data:
        type: "array"
        items:
          type: "object"
          properties:
            account_id:
              type: "integer"
              example: "4"
            stock_id:
              type: "integer"
              example: "1"
            user_id:
              type: "integer"
              example: "1"
            usd_amount:
              type: "number"
              example: "500.000000"
            share_amount:
              type: "number"
              example: "1.463151"
      timestamp:
        type: "string"
        example: "Sun, 10 Jan 2021 01:01:45 GMT"
  Delete Users:
    type: "object"
    properties:
      data:
        type: "array"
        items:
          type: "object"
          properties:
            user_id:
              type: "integer"
              example: "1"
      timestamp:
        type: "string"
        example: "Sun, 10 Jan 2021 01:01:45 GMT"
  Create Users:
    type: "object"
    properties:
      data:
        type: "array"
        items:
          type: "object"
          properties:
            user_id:
              type: "integer"
              example: "1"
            first_name:
              type: "string"
              example: "John"
            last_name:
              type: "string"
              example: "Doe"
            email:
              type: "string"
              example: "JohnDoe@gmail.com"
            address_id:
              type: "integer"
              example: "1"
      timestamp:
        type: "string"
        example: "Sun, 10 Jan 2021 01:01:45 GMT"
  Accounts:
    type: "object"
    properties:
      data:
        type: "array"
        items:
          type: "object"
          properties:
            account_id:
              type: "integer"
              example: "1"
            share_amount:
              type: "number"
              example: "1.463151"
            stock:
              type: "object"
              properties:
                stock_id:
                  type: "integer"
                  example: "1"
                symbol:
                  type: "string"
                  example: "TSLA"
            usd_amount:
              type: "number"
              example: "500.000000"
            user:
              type: "object"
              properties:
                user_id:
                  type: "integer"
                  example: "1"
                first_name:
                  type: "string"
                  example: "John"
                last_name:
                  type: "string"
                  example: "Doe"
      timestamp:
        type: "string"
        example: "Sun, 10 Jan 2021 01:01:45 GMT"
  Users:
    type: "object"
    properties:
      data:
        type: "array"
        items:
          type: "object"
          properties:
            user_id:
              type: "integer"
              example: "1"
            first_name:
              type: "string"
              example: "John"
            last_name:
              type: "string"
              example: "Doe"
            email:
              type: "string"
              example: "JohnDoe@gmail.com"
            address:
              type: "object"
              properties:
                  street:
                    type: "string"
                    example: "12345 West Ram Way"
                  postal_code:
                    type: "string"
                    example: "12345"
                  city:
                    type: "string"
                    example: "New York"
                  state:
                    type: "string"
                    example: "New York"
                  country:
                    type: "string"
                    example: "United States"
      timestamp:
        type: "string"
        example: "Sun, 10 Jan 2021 01:01:45 GMT"